Fix bundling error: Move babel-plugin-module-resolver to dependencies
The Android bundling was failing because babel-plugin-module-resolver
was in devDependencies but needs to be in dependencies for EAS builds.
Babel plugins must be available during the build process.

Fixes error: Cannot find module 'babel-plugin-module-resolver'